apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mongo-express
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
