apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
